name: play-gitterra
description: This action will let you play GitTerra game in your repository
author: GitTerra Team
branding:
  icon: "map"
  color: "blue"

runs:
  using: "composite"
  steps:
    - run: echo "Let's play GitTerra game"
      shell: "bash"

    - name: Opening the scrolls of wisdom
      uses: actions/checkout@v4
      with:
        path: "scrolls"
        # @TODO make this maximum configurable
        fetch-depth: 10000
        ref: ${{ github.ref }}

    - name: Asking our wizard to extract the inner knowledge
      id: cache-scc
      uses: actions/cache@v4
      env:
        cache-name: our-wizard
      with:
        # we don't expect SCC to change, just use the same version all the time
        path: wizard/
        key: ${{ env.cache-name }}

    - if: ${{ steps.cache-scc.outputs.cache-hit != 'true' }}
      name: Inviting a wizard from a distant land
      run: |
        mkdir -p wizard
        wget https://github.com/boyter/scc/releases/download/v3.2.0/scc_Linux_x86_64.tar.gz -O wizard/scc.gz
        tar -C wizard/ -xvf wizard/scc.gz
      shell: "bash"

    - name: Extracting the inner knowledge hidden inside the scrolls
      run: time wizard/scc scrolls/ --by-file --format json --output gitterra.json
      shell: "bash"

    - name: Transporting builders to the construction site
      uses: actions/checkout@v4
      with:
        repository: "GitTerraGame/Play-GitTerra-Action"
        path: "builders"
        #TODO: remove the ref once the action is merged
        ref: "timelapse"

    - name: Looking for a stash of existing tools
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: tool-stash
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('builders/package-lock.json') }}
        restore-keys: |
          ${{ env.cache-name }}-${{ runner.os }}-
          ${{ env.cache-name }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: Check the empty stash
      continue-on-error: true
      shell: "bash"
      run: npm list

    - name: Equipping builders with the tools
      run: (cd builders && npm ci)
      shell: "bash"

    - name: Building the city of GitTerra
      run: node builders/src/generateMap.js scrolls/.gitterra.config.js
      shell: "bash"

    - name: Generating historical records
      run: builders/src/generate_history.sh wizard/scc ./scrolls ./history
      shell: "bash"

    - name: Archive the maps in the player's library
      uses: actions/upload-artifact@v4
      with:
        name: gitterra
        path: |
          index.html
