stages:
  - play GitTerra

pages:
  stage: play GitTerra
  image: node:latest
  needs: [GitTerra]
  script:
    - echo "Deploying GitTerra page and history to GitLab Pages"
    - mkdir public/
    - mv index.html public/
    - |
      if [[ -f history.json ]]; then
        mv history.json public/
      fi
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
